import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BlogCard from "@/components/blogcard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <BlogCard image="https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp" buttonText="Read More" description="There is a heightened interest in cloud — an 
enabler for modern business
priorities like AI, carbon emissions
reduction and innovation."/>
        {children}
      </body>
    </html>
  );
}
